name: 'Set Build Variables'
description: 'Extracts and sets build variables'
outputs:
  last-tagged-version:
    description: "The last version produced by the pipeline"
    value: ${{ steps.get-last-tagged-version.outputs.last-tagged-version }}
  branch-name:
    description: "The branch name of the build run"
    value: ${{ steps.get-branch-name.outputs.branch-name }}
runs:
  using: "composite"
  steps:
    - id: get-last-tagged-version 
      run: |
        GIT_STATUS=`git status`
        echo "GIT_STATUS=$GIT_STATUS"
        echo "trying git fetch --tags..."
        git fetch --tags
        echo "listing all tags by committerdate..."
        git tag --list --sort=committerdate
        ## trying another way to get the last tagged version
        LAST_TAGGED_VERSION2=$(git tag --sort=taggerdate | tail -1)
        echo "LAST_TAGGED_VERSION2=$LAST_TAGGED_VERSION2"
        ## get the last tagged version from the tag history of the current branch - if none is found default to version '0.0.0'
        LAST_TAGGED_VERSION=$(git tag --sort=creatordate 'v*' --merged | head -n 1 | sed -Ee 's/v//g') && [ -z $LAST_TAGGED_VERSION ] && LAST_TAGGED_VERSION=0.0.0
        echo "LAST_TAGGED_VERSION=$LAST_TAGGED_VERSION"
        echo "last-tagged-version=$LAST_TAGGED_VERSION" >> $GITHUB_OUTPUT
      shell: bash
    - id: get-branch-name
      run: |
        BRANCH_NAME=`echo ${GITHUB_REF##*/} | sed -Ee 's/[_ ]/-/g'`
        echo $BRANCH_NAME
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      shell: bash