name: Package and Publish to Visual Studio Marketplace

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Set Git configuration
        run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@bots.github.com"

      - name: Install dependencies
        run: npm install

      - name: Bump version and create Git tag
        uses: Aqovia/npm-version-increment@tidyup
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: CHANGELOG.md
          sinceTag: "v0.0.17"
      
      - name: Install vsce CLI
        run: npm install -g @vscode/vsce
        
      - name: Extract extensionPack and update README
        shell: pwsh
        run: |
            # Read the extensions and convert them to Display Names and URLs
            $extensionsJSON = node -p "JSON.stringify(require('./package.json').extensionPack, null, 2)"
            $extensions = $extensionsJSON | ConvertFrom-Json

            $formatted_extensions = @()
            foreach ($extension in $extensions) {
              $dispName = $(vsce show $extension --json | ConvertFrom-Json | Select-Object -ExpandProperty displayName)
              $url = "https://marketplace.visualstudio.com/items?itemName=$($extension)"
              $formatted_extensions += "- [$dispName]($url)`n"
            }
            
            $formatted_extensions = "`n" + $formatted_extensions + "`n"
  
            $readme_content = Get-Content -Raw -Path "README.md"
  
            # Use regular expressions to find and replace the section between markers
            $regex = "(?s)(\r?\n)*<!-- EXTENSION_PACK_START -->.*?<!-- EXTENSION_PACK_END -->"
            $updated_content = $readme_content -replace $regex, $formatted_extensions
  
            # Remove any leading or trailing newlines
            $updated_content = $updated_content.Trim()
  
            # Write the updated content back to README.md
            $updated_content | Set-Content -Path "README.md" -NoNewline

      - name: Build extension and create VSIX package
        run: vsce package
  
      - name: Publish to Visual Studio Marketplace
        env:
            PERSONAL_ACCESS_TOKEN: ${{ secrets.VS_MARKETPLACE_PAT }}
        run: |
            echo "CURRENT_VERSION=${{ steps.version.outputs.current-version }}"
            echo "NEW_VERSION=${{ steps.version.outputs.new-version }}"

            # Extract the major and minor version numbers before and after the version bump
            CURRENT_MAJOR=$(echo ${{ steps.version.outputs.current-version }} | cut -d. -f1)
            CURRENT_MINOR=$(echo ${{ steps.version.outputs.current-version }} | cut -d. -f2)

            NEW_MAJOR=$(echo ${{ steps.version.outputs.new-version }} | cut -d. -f1)
            NEW_MINOR=$(echo ${{ steps.version.outputs.new-version }} | cut -d. -f2)

            # Compare the version numbers to determine if it's a pre-release or a full release
            if [ "$NEW_MAJOR" != "$CURRENT_MAJOR" ] || [ "$NEW_MINOR" != "$CURRENT_MINOR" ]; then
              # For full release versions (major or minor version changed), publish normally
              echo "Publishing full release version - ${{ steps.version.outputs.new-version }}"
              vsce publish -p $PERSONAL_ACCESS_TOKEN
            else
              # For pre-release versions (only patch version changed), publish as pre-release
              echo "Publishing pre-release version - ${{ steps.version.outputs.new-version }}"
              vsce publish --pre-release -p $PERSONAL_ACCESS_TOKEN
            fi
