name: Package and Publish
run-name : ${{ github.actor }} is running Package and Publish
on: [push, pull_request]

#defaults:
#  run:
#    shell: pwsh

jobs:
  check-vsce-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g @vscode/vsce
      - run: vsce -V

