name: Package and Publish
run-name : ${{ github.actor }} is running Package and Publish
on: [push, pull_request]

defaults:
  run:
    shell: pwsh

jobs:
  package-with-vsce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g @vscode/vsce
        shell: bash
      - run: vsce -V
        shell: bash
      - id: get-suffix
        name: Get package version suffix
        run: |
          $packageVersionSuffix = ""

          $branchName = ""
          if ($env:GITHUB_REF -match "refs/heads/(.*)") {
            $branchName = $Matches[1]
          }

          #Get version from package.json
          $packageVersionFromJson = (Get-Content package.json | ConvertFrom-Json).version

          if ($branchName -eq "master" -or $branchName -eq "main") {
            $packageVersionSuffix = "$packageVersionFromJson"
            echo "This is the default branch, so the package version will be : [$packageVersionSuffix]"
          } else {
            $packageVersionSuffix = "$packageVersionFromJson.$env:GITHUB_RUN_ID"
            echo "This is not the default branch, so a package version suffix: [$packageVersionSuffix] will be used."
          }

          echo "package-version-suffix=$packageVersionSuffix" >> $env:GITHUB_OUTPUT
      - run: env
      - id: "package-vsix"
        name : "Package VSIX"
        run: |
          $packageVersionSuffix = (Get-Content $env:GITHUB_OUTPUT | ConvertFrom-StringData)."package-version-suffix"
          echo "packageVersionSuffix=$packageVersionSuffix"

          vsce package --yarn --packagePath aqovia-vscode-extension-pack-$packageVersionSuffix.vsix


